ALTER TABLE de.DEPOSIT_CUSTOMER_RELATION
DISABLE CONSTRAINT DEP_CUST_REL_DEP_ID_FK;
ALTER TABLE de.PRODUCT
DISABLE CONSTRAINT PRD_PLTFRM_ID_FK;
ALTER TABLE de.PRODUCT
DISABLE CONSTRAINT PRD_ROLL_SETT_PRFL_ID_FK;
ALTER TABLE de.PRODUCT
DISABLE CONSTRAINT PRD_OPRTN_GRP_ID_FK;
ALTER TABLE PRODUCT_OPERATION
DISABLE CONSTRAINT  PRD_OPRTN_OPRTN_GRP_ID_FK;
ALTER TABLE de.ROLEOVER_SETTLEMENT_PROFILE
DISABLE CONSTRAINT ROP_PRODUCT_ID_FK;

TRUNCATE TABLE de.PRODUCT
TRUNCATE TABLE de.CUSTOMER_RELATION_PROFILE
TRUNCATE TABLE de.DEPOSIT
TRUNCATE TABLE de.DEPOSIT_CUSTOMER_RELATION
TRUNCATE TABLE de.PLATFORM


ALTER TABLE de.DEPOSIT_CUSTOMER_RELATION
ENABLE CONSTRAINT DEP_CUST_REL_DEP_ID_FK;
ALTER TABLE de.PRODUCT
ENABLE CONSTRAINT PRD_PLTFRM_ID_FK;
ALTER TABLE de.PRODUCT
ENABLE CONSTRAINT PRD_ROLL_SETT_PRFL_ID_FK;
ALTER TABLE de.PRODUCT
ENABLE CONSTRAINT PRD_OPRTN_GRP_ID_FK;
ALTER TABLE PRODUCT_OPERATION
ENABLE CONSTRAINT  PRD_OPRTN_OPRTN_GRP_ID_FK;
ALTER TABLE de.ROLEOVER_SETTLEMENT_PROFILE
ENABLE CONSTRAINT ROP_PRODUCT_ID_FK;

COMMIT ;

insert into de.platform (ID, CODE, TITLE, IS_PROFITABLE, HAS_DEPOSIT_CERTIFICATE, HAS_ROLLOVER_SETTLEMENT, HAS_CHEQUE, HAS_WARRANTY_LENDING, HAS_TERM_DURATION, HAS_DRAW, HAS_PRIORITY_SECURITIES, INSERT_USER_ID, INSERT_ORGANIZATION_ID, INSERT_DATE, MODIFY_USER_ID, MODIFY_ORGANIZATION_ID, MODIFY_DATE, VERSION, MAX_OPENED_DEPOSIT)
values ('642', '1', 'سپرده قرض الحسنه', '0', '0', '0', '0', '0', '0', '1', '0', '1920', '1111', '12-MAY-18 07.40.40.916000 PM', null, null, null, '1', '1000');

insert into de.product (ID, CODE, PERSIAN_NAME, ENGLISH_NAME, MAJOR_ID, CURRENCY_ID, PLATFORM_ID, STATUS_ID, EFFECTIVE_DATE, DEACTIVE_DATE, HAS_TERM_DURATION, TERM_UNIT_ID, MIN_TERM_DURATION, MAX_TERM_DURATION, HAS_WARRANTY_LENDING, MIN_SCORE_AMOUNT, HAS_DEPOSIT_CERTIFICATE, HAS_PASSBOOK, HAS_CHEQUE, HAS_BACKUP, IS_BACKUP, HAS_CARD, OPENING_LOCATION_ID, HAS_DORMANCY, DORMANCY_DURATION, MIN_DORMANCY_AMOUNT, MIN_OPENING_AMOUNT, MIN_BALANCE_AMOUNT, STAMP_DUTY_AMOUNT, HAS_GROUP_OPENING, HAS_DRAW, SEDIMENT_AMOUNT, IS_PROFITABLE, PROFIT_PROFILE_ID, PROFIT_METHOD_ID, PROFIT_RATE_PROFILE_ID, BREAKAGE_PROFILE_ID, ROLLOVER_SETTLEMENT_PROFILE_ID, HAS_PRIORITY_SECURITIES, HAS_DEFINITIVE_PROFIT, MIN_ALERT_AMOUNT, HAS_INQUIRY, INSERT_USER_ID, INSERT_ORGANIZATION_ID, INSERT_DATE, MODIFY_USER_ID, MODIFY_ORGANIZATION_ID, MODIFY_DATE, VERSION, DEPOSIT_TERM_ID, HAS_AML_CONTROL, SEND_SMS, OPERATION_GROUP_ID, MAX_SHARED_DEPOSIT, MAX_SINGLE_DEPOSIT, STAMP_DUTY_METHOD, STATUS_DATE, DORMANCY_DURATION_UNIT, MIN_DURATION_FOR_NOT_DEMANDED, UNIT_FOR_NOT_DEMANDED, MAJOR_FOR_STAMP_DUTY_AMOUNT, HAS_INTRODUCER, HAS_SEDIMENT, CUSTOMER_RELATION_PROFILE_ID,HAS_TRANSFERABILITY)
values ('1', '11', 'قرض الحسنه پس انداز اشخاص حقيقي', 'Real Customer Qarzolhasaneh', '1', '2994', '642', '10381', to_date('13-05-2018', 'dd-mm-yyyy'), to_date('13-05-2918', 'dd-mm-yyyy'), '0', null, null, null, '0', '0', '0', '1', '0', '0', '1', '1', '10465', '0', null, null, '0', '0', null, '1', '1', null, '0', null, null, null, null, null, '0', '0', '10000', '1', '1920', '1', '12-MAY-18 07.40.40.916000 PM', null, null, null, '1', null, '1', '1', null, '100', '1000', null, to_date('13-05-2018', 'dd-mm-yyyy'), null, null, null, null, '0', '0', '661',0);

insert into de.customer_relation_profile (ID, CODE, TITLE, EFFECTIVE_DATE, RESIDENCY_ID, MIN_OPENER_AGE, MIN_OWNER_AGE, MIN_SIGNER_AGE, INSERT_USER_ID, INSERT_ORGANIZATION_ID, INSERT_DATE, MODIFY_USER_ID, MODIFY_ORGANIZATION_ID, MODIFY_DATE, VERSION, ALLOWED_OPENER, LEGAL_PERSON_OWNER_TYPE, LEGAL_PERSON_TYPE, NATIONALITY, OWNER_GENDER, PERSON_TYPE)
values ('661', '111', 'شرايط عمومي مرتبطين حقيقي', to_date('13-05-2018', 'dd-mm-yyyy'), '10475', '18', '18', '18', '1920', '1111', '12-MAY-18 08.20.54.952000 PM', null, null, null, '1', null, null, null, null, null, null);

COMMIT ;